### ISSUE TITLE
highlight with wrong position

### ISSUE THREAD

**Issue by mutefrank** [mistic100/jquery-highlighttextarea#58]
I try to highlight some words in text as below, the range set up as [87,100], the expected highlight words should be 'Bestellnummer' but its actual highlight word is "llnummer:#12" . any idea? is it because of space and return characters? 
>&nbsp;Meine Bestellungen 
>&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;Mein Konto 
>&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;Amazon.de 
>
>
>&nbsp;Versandbestätigung
>Bestellnummer: #123123123123

![qq 20150616173418](https://cloud.githubusercontent.com/assets/323852/8180074/01abe9fc-144e-11e5-9139-1fbe0fcffd94.png)

**Comment by mutefrank** [comment]
and my browser is IE 11

**Comment by mistic100** [comment]
could you reformat you message with proper Markdown syntax ?
it's totally unintelligible

**Comment by mutefrank** [comment]
updated the message.  please help to have a check.

**Comment by mistic100** [comment]
you have 5 new lines, and a drift of 5 chars, so yes you must count the line breaks (it's a char)

why don't you use the "words" option instead ? seems much more appropriated to highlight a specific word

**Comment by mutefrank** [comment]
I could not use "words" option as I need to calculate the offset/span from backend service. Would you please recommend a way to accomplish it with "ranges" option?

**Comment by mistic100** [comment]
just count the new line chars

**Comment by mutefrank** [comment]
okay.. this workaround works.
