### ISSUE TITLE
Update the list of ranges as the program runs?

### ISSUE THREAD

**Issue by jonathandeiven** [mistic100/jquery-highlighttextarea#59]
So basically, I want to add to the ranges of words to be highlighted as the program executes. I'll be using an array to contain the args, and that seems to be working perfectly. However, the highlighted text doesn't update when you call it again with the updated list of arguments. Is there a way to have the list of ranges to be highlighted update?

    var args = new Array();
    args.push({ color: '#c1f5b0', start: 0, length: 5 })

    $('#demo9').highlightTextarea({
          ranges: args    
    });

    //At this point, only (0, 5) should be highlighted.

    args.push({ color: '#c1f5b0', start: 6, length: 5 })

    $('#demo9').highlightTextarea({
          ranges: args     
    });

    //At this point, both (0, 5) and (6,11) should be highlighted. But only (0, 5) remains highlighted.

**Comment by jonathandeiven** [comment]
It seems that you can simply destroy the old highlighting, and rebuild it. So for example, adding
$('#demo7').highlightTextarea('destroy'); 
right after the second array push would build a new highlighted area object.

Thanks so much for building this wonderful API! A++

**Comment by mistic100** [comment]
no need to destroy

```js
$('#demo7').highlightTextarea('setRanges', args); 
```
